import type { AppProps } from "next/app";
import Head from "next/head";
import { WindowStateProvider } from "../contexts/window-state";
import { useEffect, useState } from "react";
import { WindowType } from "../contexts/window-state/types";
import { useRouter } from "next/router";

import "../styles/globals.css";

function MyApp({ Component, pageProps }: AppProps) {
  const [windowType, setWindowType] = useState<WindowType>("main");
  const router = useRouter();

  useEffect(() => {
    const type = router.route === "/[...popup]" ? "popup" : "main";
    setWindowType(type);
  }, [router]);

  return (
    <WindowStateProvider windowType={windowType}>
      <Head>
        <title>Multi Window App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </WindowStateProvider>
  );
}

export default MyApp;
